import type { AssetInput } from '@pascal-app/core'


// Möbel-Katalog-Assets: Basis über NEXT_PUBLIC_ASSETS_CDN_URL (Standard: Plixa R2).
// Ersetzt Pascals Supabase-Host — im Live-Betrieb lädt der Katalog von R2, nicht von Supabase.
const ASSET_BASE =
  process.env.NEXT_PUBLIC_ASSETS_CDN_URL || 'https://pub-4572f09e779c444fa5bd77e378de46df.r2.dev'

export const CATALOG_ITEMS: AssetInput[] = [
  {
    id: 'cactus',
    category: 'furniture',
    name: 'Cactus',
    tags: [
      'cactus',
      'rack',
      'stand',
      'hanger',
      'sculpture',
      'decor',
      'modern',
      'contemporary',
      'pop',
      'green',
      'organizer',
      'storage',
      'sculptural',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/cactus/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/cactus/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/cactus/floor-plan.png`,
    dimensions: [0.34, 0.39, 0.27],
    offset: [-0.0039, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tv-stand',
    category: 'furniture',
    name: 'TV Stand',
    tags: ['floor', 'storage'],
    thumbnail:
      `${ASSET_BASE}/items/system/tv-stand/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/tv-stand/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/tv-stand/floor-plan.png`,
    dimensions: [1.86, 0.35, 0.32],
    offset: [0, 0.2066, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.35 },
  },
  {
    id: 'dining-table-mo9ms5yh',
    category: 'furniture',
    name: 'Dining table',
    tags: [
      'dining',
      'table',
      'dinette',
      'wood',
      'oak',
      'modern',
      'minimalist',
      'scandinavian',
      'rectangular',
      'kitchen',
      'mealtime',
      'entertaining',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/dining-table-mo9ms5yh/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/dining-table-mo9ms5yh/models/item_model_Sffq4hIGw8R3keLh.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/dining-table-mo9ms5yh/floor-plan.png`,
    dimensions: [2, 0.77, 0.91],
    offset: [0.0002, 0.3793, -0.0026],
    rotation: [0, 0, 0],
    scale: [2, 2, 2],
    surface: { height: 0.77 },
  },
  {
    id: 'single-bed',
    category: 'furniture',
    name: 'Single Bed',
    tags: ['floor', 'bedroom'],
    thumbnail:
      `${ASSET_BASE}/items/system/single-bed/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/single-bed/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/single-bed/floor-plan.png`,
    dimensions: [1.08, 0.6, 2.14],
    offset: [-0.0024, 0, -0.013],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'livingroom-chair',
    category: 'furniture',
    name: 'Livingroom Chair',
    tags: [
      'chair',
      'armchair',
      'seating',
      'lounge',
      'upholstered',
      'modern',
      'fabric',
      'furniture',
      'minimalist',
      'comfort',
      'accent',
      'lounger',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/livingroom-chair/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/livingroom-chair/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/livingroom-chair/floor-plan.png`,
    dimensions: [1.1, 0.75, 1.07],
    offset: [0, 0.0001, 0.0053],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'small-indoor-plant',
    category: 'furniture',
    name: 'Small Plant',
    tags: ['countertop', 'decor', 'vegetation'],
    thumbnail:
      `${ASSET_BASE}/items/system/small-indoor-plant/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/small-indoor-plant/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/small-indoor-plant/floor-plan.png`,
    dimensions: [0.4, 0.67, 0.38],
    offset: [-0.0106, 0, 0.0067],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'column',
    category: 'furniture',
    name: 'Column',
    tags: [
      'column',
      'pillar',
      'pedestal',
      'plinth',
      'stand',
      'marble',
      'stone',
      'classical',
      'roman',
      'greek',
      'decorative',
      'architectural',
      'antique',
      'support',
      'base',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/column/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/column/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/column/floor-plan.png`,
    dimensions: [0.5, 2.5, 0.5],
    offset: [0, 1.25, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'barbell',
    category: 'furniture',
    name: 'Barbell',
    tags: [
      'barbell',
      'weight',
      'steel',
      'iron',
      'metal',
      'gym',
      'fitness',
      'industrial',
      'workout',
      'strength',
      'training',
      'lifting',
      'chrome',
      'exercise',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/barbell/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/barbell/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/barbell/floor-plan.png`,
    dimensions: [0.38, 0.38, 1.72],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toy',
    category: 'furniture',
    name: 'Toy',
    tags: ['floor', 'kids', 'decor'],
    thumbnail:
      `${ASSET_BASE}/items/system/toy/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/toy/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/toy/floor-plan.png`,
    dimensions: [0.29, 0.49, 0.34],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'barbell-stand',
    category: 'furniture',
    name: 'Barbell Stand',
    tags: [
      'rack',
      'stand',
      'holder',
      'storage',
      'metal',
      'steel',
      'industrial',
      'fitness',
      'gym',
      'weightlifting',
      'training',
      'minimalist',
      'black',
      'organizer',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/barbell-stand/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/barbell-stand/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/barbell-stand/floor-plan.png`,
    dimensions: [1.34, 1.22, 1.72],
    offset: [-0.0173, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'books',
    category: 'furniture',
    name: 'Books',
    tags: [
      'books',
      'novels',
      'literature',
      'reading',
      'vintage',
      'classic',
      'decorative',
      'paper',
      'leather',
      'library',
      'study',
      'office',
      'decor',
      'shelf',
      'antique',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/books/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/books/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/books/floor-plan.png`,
    dimensions: [0.22, 0.22, 0.18],
    offset: [-0.0851, 0.003, 0.0209],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'stool',
    category: 'furniture',
    name: 'Stool',
    tags: ['floor', 'seating'],
    thumbnail:
      `${ASSET_BASE}/items/system/stool/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/stool/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/stool/floor-plan.png`,
    dimensions: [0.52, 1.16, 0.55],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'pool-table',
    category: 'furniture',
    name: 'Pool table',
    tags: [
      'pool',
      'billiards',
      'snooker',
      'table',
      'recreation',
      'leisure',
      'entertainment',
      'wood',
      'felt',
      'gaming',
      'traditional',
      'luxury',
      'classic',
      'hobby',
      'furniture',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/pool-table/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/pool-table/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/pool-table/floor-plan.png`,
    dimensions: [2.11, 0.98, 3.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bookshelf',
    category: 'furniture',
    name: 'Bookshelf',
    tags: [
      'bookshelf',
      'bookcase',
      'shelving',
      'storage',
      'organizer',
      'modern',
      'minimalist',
      'wood',
      'metal',
      'industrial',
      'library',
      'office',
      'furniture',
      'display',
      'timber',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/bookshelf/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/bookshelf/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/bookshelf/floor-plan.png`,
    dimensions: [0.93, 1.99, 0.33],
    offset: [0, 0, 0.0032],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'coat-rack',
    category: 'furniture',
    name: 'Coat Rack',
    tags: [
      'coatrack',
      'rack',
      'hanger',
      'valet',
      'organizer',
      'storage',
      'entryway',
      'hallway',
      'minimalist',
      'metal',
      'wood',
      'mudroom',
      'hooks',
      'clothes',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/coat-rack/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/coat-rack/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/coat-rack/floor-plan.png`,
    dimensions: [0.33, 1.76, 0.33],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'car-toy',
    category: 'furniture',
    name: 'Car Toy',
    tags: [
      'car',
      'toy',
      'vehicle',
      'racer',
      'play',
      'nursery',
      'playroom',
      'wooden',
      'vintage',
      'decor',
      'kids',
      'child',
      'classic',
      'miniature',
      'hobby',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/car-toy/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/car-toy/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/car-toy/floor-plan.png`,
    dimensions: [0.31, 0.38, 0.6],
    offset: [0.0005, 0.0005, -0.0075],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bedside-table',
    category: 'furniture',
    name: 'Bedside Table',
    tags: [
      'nightstand',
      'table',
      'bedroom',
      'storage',
      'wood',
      'modern',
      'minimalist',
      'stand',
      'drawer',
      'furniture',
      'cabinet',
      'bedside',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/bedside-table/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/bedside-table/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/bedside-table/floor-plan.png`,
    dimensions: [0.45, 0.48, 0.46],
    offset: [0.0005, 0, -0.0062],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.48 },
  },
  {
    id: 'sofa',
    category: 'furniture',
    name: 'Sofa',
    tags: ['floor', 'seating'],
    thumbnail:
      `${ASSET_BASE}/items/system/sofa/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/sofa/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/sofa/floor-plan.png`,
    dimensions: [2.06, 0.74, 1.01],
    offset: [-0.0023, 0.009, 0.0459],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bunkbed',
    category: 'furniture',
    name: 'Bunkbed',
    tags: [
      'bunkbed',
      'bed',
      'sleeper',
      'loft',
      'bedroom',
      'kids',
      'wood',
      'metal',
      'modern',
      'sleeping',
      'ladder',
      'rustic',
      'dormitory',
      'furniture',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/bunkbed/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/bunkbed/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/bunkbed/floor-plan.png`,
    dimensions: [1.65, 1.55, 0.99],
    offset: [0, 0, -0.0886],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'my-leather-couch-modp80ha',
    category: 'furniture',
    name: 'My leather couch',
    thumbnail:
      `${ASSET_BASE}/items/system/my-leather-couch-modp80ha/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/my-leather-couch-modp80ha/models/item_model_kgORhH5vwFK8xub0.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/my-leather-couch-modp80ha/floor-plan.png`,
    dimensions: [2, 0.67, 0.61],
    offset: [-0.0005, 0.3228, -0.004],
    rotation: [0, 0, 0],
    scale: [2, 2, 2],
  },
  {
    id: 'office-table',
    category: 'furniture',
    name: 'Office Table',
    tags: [
      'desk',
      'table',
      'workstation',
      'furniture',
      'office',
      'work',
      'study',
      'writing',
      'modern',
      'minimalist',
      'industrial',
      'wood',
      'metal',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/office-table/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/office-table/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/office-table/floor-plan.png`,
    dimensions: [1.51, 0.76, 0.62],
    offset: [-0.0001, 0, -0.0052],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.75 },
  },
  {
    id: 'dining-table',
    category: 'furniture',
    name: 'Dining Table',
    tags: [
      'table',
      'dining',
      'furniture',
      'wood',
      'modern',
      'minimalist',
      'kitchen',
      'eating',
      'surface',
      'contemporary',
      'gathering',
      'walnut',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/dining-table/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/dining-table/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/dining-table/floor-plan.png`,
    dimensions: [2.16, 0.7, 0.95],
    offset: [0, 0, -0.0077],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.7 },
  },
  {
    id: 'guitar',
    category: 'furniture',
    name: 'Guitar',
    tags: [
      'guitar',
      'instrument',
      'musical',
      'wood',
      'acoustic',
      'vintage',
      'classic',
      'decor',
      'mahogany',
      'string',
      'art',
      'hobby',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/guitar/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/guitar/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/guitar/floor-plan.png`,
    dimensions: [0.4, 1.18, 0.09],
    offset: [-0.0009, 0.3197, -0.0129],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'trash-bin',
    category: 'furniture',
    name: 'Trash Bin',
    tags: ['floor'],
    thumbnail:
      `${ASSET_BASE}/items/system/trash-bin/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/trash-bin/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/trash-bin/floor-plan.png`,
    dimensions: [0.35, 0.59, 0.42],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'recessed-light',
    category: 'furniture',
    name: 'Recessed Light',
    tags: [
      'recessed',
      'downlight',
      'spotlight',
      'lighting',
      'fixture',
      'modern',
      'minimalist',
      'metal',
      'aluminum',
      'luminaire',
      'ambient',
      'illumination',
      'architectural',
      'can',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/recessed-light/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/recessed-light/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/recessed-light/floor-plan.png`,
    dimensions: [0.23, 0.06, 0.23],
    offset: [0, 0.0057, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    recessed: true,
    interactive: {
      controls: [
        { kind: 'toggle' },
        {
          kind: 'slider',
          label: 'Intensity',
          min: 0,
          max: 100,
          unit: '%',
          displayMode: 'dial',
          default: 100,
        },
      ],
      effects: [{ kind: 'light', intensityRange: [0, 2], color: '#ffffff', offset: [0, -0.1, 0] }],
    },
  },
  {
    id: 'shelf',
    category: 'furniture',
    name: 'Shelf',
    tags: [
      'shelf',
      'shelving',
      'rack',
      'ledge',
      'storage',
      'organization',
      'display',
      'bookshelf',
      'modern',
      'minimalist',
      'furniture',
      'decor',
      'contemporary',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/shelf/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/shelf/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/shelf/floor-plan.png`,
    dimensions: [0.74, 0.04, 0.32],
    offset: [0, 0.02, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    surface: { height: 0.04 },
  },
  {
    id: 'table-lamp',
    category: 'furniture',
    name: 'Table Lamp',
    tags: ['countertop', 'lighting'],
    thumbnail:
      `${ASSET_BASE}/items/system/table-lamp/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/table-lamp/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/table-lamp/floor-plan.png`,
    dimensions: [0.29, 0.74, 0.67],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ceiling-lamp',
    category: 'furniture',
    name: 'Ceiling Lamp',
    tags: [
      'lamp',
      'light',
      'chandelier',
      'pendant',
      'luminaire',
      'fixture',
      'lighting',
      'modern',
      'minimalist',
      'glass',
      'metal',
      'indoor',
      'illumination',
      'interior',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/ceiling-lamp/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/ceiling-lamp/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/ceiling-lamp/floor-plan.png`,
    dimensions: [0.55, 0.86, 0.55],
    offset: [0, 0.8545, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        { kind: 'toggle' },
        {
          kind: 'slider',
          label: 'Intensity',
          min: 0,
          max: 100,
          unit: '%',
          displayMode: 'dial',
          default: 100,
        },
      ],
      effects: [{ kind: 'light', intensityRange: [0, 2], color: '#ffffff', offset: [0, -0.3, 0] }],
    },
  },
  {
    id: 'closet',
    category: 'furniture',
    name: 'Closet',
    tags: [
      'closet',
      'wardrobe',
      'armoire',
      'cabinet',
      'storage',
      'organization',
      'wood',
      'bedroom',
      'modern',
      'minimalist',
      'clothing',
      'apparel',
      'cupboard',
      'locker',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/closet/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/closet/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/closet/floor-plan.png`,
    dimensions: [1.95, 2.26, 0.6],
    offset: [0, 0, -0.0141],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'coffee-table',
    category: 'furniture',
    name: 'Coffee Table',
    tags: [
      'table',
      'cocktail',
      'wood',
      'modern',
      'minimalist',
      'furniture',
      'living',
      'lounge',
      'walnut',
      'metal',
      'glass',
      'surface',
      'decor',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/coffee-table/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/coffee-table/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/coffee-table/floor-plan.png`,
    dimensions: [1.72, 0.3, 1.04],
    offset: [0, 0, 0.0089],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.3 },
  },
  {
    id: 'dining-chair',
    category: 'furniture',
    name: 'Dining Chair',
    tags: [
      'chair',
      'seating',
      'dining',
      'furniture',
      'modern',
      'wood',
      'upholstered',
      'kitchen',
      'seat',
      'minimalist',
      'timber',
      'bistro',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/dining-chair/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/dining-chair/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/dining-chair/floor-plan.png`,
    dimensions: [0.47, 0.87, 0.5],
    offset: [0, 0, 0.0016],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'dresser',
    category: 'furniture',
    name: 'Dresser',
    tags: [
      'dresser',
      'chest',
      'bureau',
      'storage',
      'bedroom',
      'drawers',
      'wood',
      'modern',
      'organization',
      'cabinet',
      'rustic',
      'minimalist',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/dresser/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/dresser/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/dresser/floor-plan.png`,
    dimensions: [1.23, 0.73, 0.61],
    offset: [0, 0, -0.0066],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.73 },
  },
  {
    id: 'ikea-kallax-1x4-moa2y49n',
    category: 'furniture',
    name: 'Ikea Kallax 2x4',
    tags: [
      'shelf',
      'bookcase',
      'shelving',
      'storage',
      'organizer',
      'cubby',
      'cube',
      'scandinavian',
      'modern',
      'minimalist',
      'wood',
      'laminate',
      'display',
      'modular',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/ikea-kallax-1x4-moa2y49n/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/ikea-kallax-1x4-moa2y49n/models/item_model_ocVHS1SWDex5DeYc.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/ikea-kallax-1x4-moa2y49n/floor-plan.png`,
    dimensions: [1.09, 2.06, 0.55],
    offset: [0, -0.0053, 0],
    rotation: [0, 0, 0],
    scale: [1.4, 1.4, 1.4],
  },
  {
    id: 'indoor-plant',
    category: 'furniture',
    name: 'Indoor Plant',
    tags: [
      'plant',
      'greenery',
      'botanical',
      'foliage',
      'houseplant',
      'organic',
      'natural',
      'modern',
      'minimalist',
      'tropical',
      'decor',
      'accent',
      'green',
      'ceramic',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/indoor-plant/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/indoor-plant/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/indoor-plant/floor-plan.png`,
    dimensions: [0.69, 1.63, 0.83],
    offset: [-0.0506, 0, 0.0664],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ironing-board',
    category: 'furniture',
    name: 'Ironing Board',
    tags: [
      'ironing',
      'board',
      'laundry',
      'foldable',
      'metal',
      'utility',
      'pressing',
      'collapsible',
      'stand',
      'table',
      'organization',
      'industrial',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/ironing-board/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/ironing-board/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/ironing-board/floor-plan.png`,
    dimensions: [1.31, 0.96, 0.48],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'double-bed',
    category: 'furniture',
    name: 'Double Bed',
    tags: [
      'bed',
      'bedstead',
      'double',
      'frame',
      'bedroom',
      'sleeping',
      'modern',
      'minimalist',
      'upholstered',
      'wood',
      'sleep',
      'furniture',
      'contemporary',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/double-bed/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/double-bed/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/double-bed/floor-plan.png`,
    dimensions: [1.52, 0.71, 2],
    offset: [0.0042, 0, -0.0277],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'floor-lamp',
    category: 'furniture',
    name: 'Floor Lamp',
    tags: [
      'lamp',
      'luminaire',
      'light',
      'torchere',
      'lighting',
      'illumination',
      'metal',
      'brass',
      'modern',
      'minimalist',
      'industrial',
      'decor',
      'ambient',
      'reading',
      'sleek',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/floor-lamp/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/floor-lamp/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/floor-lamp/floor-plan.png`,
    dimensions: [0.7, 1.86, 0.69],
    offset: [0.0341, 0.0045, 0.0219],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    interactive: {
      controls: [
        { kind: 'toggle' },
        {
          kind: 'slider',
          label: 'Intensity',
          min: 0,
          max: 100,
          unit: '%',
          displayMode: 'dial',
          default: 100,
        },
      ],
      effects: [{ kind: 'light', intensityRange: [0, 2], color: '#ffffff', offset: [0, 1.4, 0] }],
    },
  },
  {
    id: 'herman-miller-aeron-mo8x36k9',
    category: 'furniture',
    name: 'Herman Miller Aeron',
    tags: ['office'],
    thumbnail:
      `${ASSET_BASE}/items/system/herman-miller-aeron-mo8x36k9/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/herman-miller-aeron-mo8x36k9/models/item_model_YshL4maC8cHtry5c.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/herman-miller-aeron-mo8x36k9/floor-plan.png`,
    dimensions: [0.67, 1.06, 0.66],
    offset: [-0.0013, 0.5256, 0.0028],
    rotation: [0, 0, 0],
    scale: [1.05, 1.05, 1.05],
  },
  {
    id: 'easel',
    category: 'furniture',
    name: 'Easel',
    tags: [
      'easel',
      'stand',
      'tripod',
      'art',
      'studio',
      'wood',
      'display',
      'canvas',
      'atelier',
      'presentation',
      'wooden',
      'sketching',
      'painting',
      'decor',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/easel/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/easel/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/easel/floor-plan.png`,
    dimensions: [0.99, 2.32, 0.55],
    offset: [0, 0.0402, 0.0116],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'lounge-chair',
    category: 'furniture',
    name: 'Lounge Chair',
    tags: [
      'chair',
      'armchair',
      'seating',
      'lounge',
      'seat',
      'modern',
      'contemporary',
      'minimalist',
      'comfort',
      'relaxation',
      'upholstered',
      'interior',
      'furniture',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/lounge-chair/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/lounge-chair/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/lounge-chair/floor-plan.png`,
    dimensions: [0.68, 1.03, 1.26],
    offset: [0, 0.0034, 0.0894],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'office-chair',
    category: 'furniture',
    name: 'Office Chair',
    tags: [
      'chair',
      'seating',
      'ergonomic',
      'swivel',
      'office',
      'desk',
      'mesh',
      'leather',
      'modern',
      'task',
      'workspace',
      'professional',
      'computer',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/office-chair/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/office-chair/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/office-chair/floor-plan.png`,
    dimensions: [0.66, 1.16, 0.69],
    offset: [0.0024, 0.0015, 0.0332],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'piano',
    category: 'furniture',
    name: 'Piano',
    tags: [
      'piano',
      'instrument',
      'musical',
      'grand',
      'upright',
      'keyboard',
      'wood',
      'polished',
      'lacquer',
      'ebony',
      'classic',
      'traditional',
      'music',
      'entertainment',
      'luxury',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/piano/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/piano/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/piano/floor-plan.png`,
    dimensions: [1.54, 1.44, 0.69],
    offset: [0, 0, 0.0162],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'picture',
    category: 'furniture',
    name: 'Picture',
    tags: [
      'picture',
      'frame',
      'art',
      'artwork',
      'print',
      'canvas',
      'decor',
      'modern',
      'abstract',
      'minimalist',
      'decorative',
      'glass',
      'wood',
      'illustration',
      'portrait',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/picture/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/picture/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/picture/floor-plan.png`,
    dimensions: [1.47, 0.82, 0.06],
    offset: [0, 0.41, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'rectangular-carpet',
    category: 'furniture',
    name: 'Rectangular Carpet',
    tags: [
      'carpet',
      'rug',
      'mat',
      'textile',
      'woven',
      'rectangular',
      'modern',
      'wool',
      'cotton',
      'minimalist',
      'decor',
      'plush',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/rectangular-carpet/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/rectangular-carpet/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/rectangular-carpet/floor-plan.png`,
    dimensions: [2.78, 0.04, 1.81],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.03 },
  },
  {
    id: 'round-mirror',
    category: 'furniture',
    name: 'Rounded Mirror',
    tags: [
      'mirror',
      'glass',
      'reflective',
      'circular',
      'oval',
      'modern',
      'minimalist',
      'contemporary',
      'scandinavian',
      'vanity',
      'decor',
      'curved',
      'reflection',
      'grooming',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/round-mirror/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/round-mirror/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/round-mirror/floor-plan.png`,
    dimensions: [0.57, 0.57, 0.05],
    offset: [0, 0.2848, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'round-carpet',
    category: 'furniture',
    name: 'Round Carpet',
    tags: [
      'carpet',
      'rug',
      'mat',
      'circular',
      'modern',
      'minimalist',
      'scandinavian',
      'textile',
      'woven',
      'decor',
      'accent',
      'wool',
      'fiber',
      'interior',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/round-carpet/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/round-carpet/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/round-carpet/floor-plan.png`,
    dimensions: [1.99, 0.05, 1.99],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.04 },
  },
  {
    id: 'threadmill',
    category: 'furniture',
    name: 'Threadmill',
    tags: ['floor', 'fitness'],
    thumbnail:
      `${ASSET_BASE}/items/system/threadmill/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/threadmill/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/threadmill/floor-plan.png`,
    dimensions: [2.1, 1.45, 0.9],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'standing-desk-mo8wgz95',
    category: 'furniture',
    name: 'Standing Desk',
    tags: ['office'],
    thumbnail:
      `${ASSET_BASE}/items/system/standing-desk-mo8wgz95/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/standing-desk-mo8wgz95/models/item_model_zzZ58018waP8VY6Z.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/standing-desk-mo8wgz95/floor-plan.png`,
    dimensions: [1.41, 0.85, 0.68],
    offset: [0, 0.4203, 0.0019],
    rotation: [0, 0, 0],
    scale: [1.4, 1.4, 1.4],
  },
  {
    id: 'sprinkler',
    category: 'appliance',
    name: 'Sprinkler',
    tags: ['ceiling', 'safety'],
    thumbnail:
      `${ASSET_BASE}/items/system/sprinkler/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/sprinkler/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/sprinkler/floor-plan.png`,
    dimensions: [0.09, 0.04, 0.09],
    offset: [0, 0.0386, 0],
    rotation: [Math.PI, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
  },
  {
    id: 'exit-sign',
    category: 'appliance',
    name: 'Exit Sign',
    tags: [
      'sign',
      'signage',
      'exit',
      'emergency',
      'safety',
      'wayfinding',
      'directional',
      'lighting',
      'led',
      'commercial',
      'industrial',
      'marker',
      'egress',
      'appliance',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/exit-sign/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/exit-sign/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/exit-sign/floor-plan.png`,
    dimensions: [0.54, 0.27, 0.1],
    offset: [0, 0.0036, 0.0452],
    rotation: [0, 0, 0],
    scale: [0.6, 0.5, 0.7],
    attachTo: 'wall-side',
  },
  {
    id: 'sewing-machine',
    category: 'appliance',
    name: 'Sewing Machine',
    tags: [
      'sewing',
      'machine',
      'appliance',
      'tailor',
      'craft',
      'hobby',
      'textile',
      'metal',
      'plastic',
      'vintage',
      'modern',
      'industrial',
      'mending',
      'stitching',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/sewing-machine/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/sewing-machine/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/sewing-machine/floor-plan.png`,
    dimensions: [0.83, 0.68, 0.32],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'television',
    category: 'appliance',
    name: 'Television',
    tags: ['floor', 'electronics'],
    thumbnail:
      `${ASSET_BASE}/items/system/television/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/television/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/television/floor-plan.png`,
    dimensions: [1.62, 1.07, 0.38],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'power-outlet-moa09g0o',
    category: 'appliance',
    name: 'Power Outlet',
    tags: ['electric'],
    thumbnail:
      `${ASSET_BASE}/items/system/power-outlet-moa09g0o/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/power-outlet-moa09g0o/models/item_model_PTDhACPTrrrtLLeI.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/power-outlet-moa09g0o/floor-plan.png`,
    dimensions: [0.09, 0.09, 0.03],
    offset: [0, 0.045, 0.0117],
    rotation: [0, 0, 0],
    scale: [0.09, 0.09, 0.09],
    attachTo: 'wall-side',
  },
  {
    id: 'ac-block',
    category: 'appliance',
    name: 'AC block',
    tags: [
      'conditioner',
      'cooler',
      'hvac',
      'cooling',
      'appliance',
      'vent',
      'modern',
      'minimalist',
      'metal',
      'industrial',
      'white',
      'utility',
      'ventilation',
      'unit',
      'climate',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/ac-block/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/ac-block/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/ac-block/floor-plan.png`,
    dimensions: [1.06, 0.95, 1.06],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [0.79, 0.79, 0.79],
  },
  {
    id: 'stereo-speaker',
    category: 'appliance',
    name: 'Stereo Speaker',
    tags: ['floor', 'electronics'],
    thumbnail:
      `${ASSET_BASE}/items/system/stereo-speaker/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/stereo-speaker/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/stereo-speaker/floor-plan.png`,
    dimensions: [0.23, 1, 0.34],
    offset: [0, 0, -0.0129],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'thermostat',
    category: 'appliance',
    name: 'Thermostat',
    tags: ['wall', 'climate', 'electrical'],
    thumbnail:
      `${ASSET_BASE}/items/system/thermostat/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/thermostat/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/thermostat/floor-plan.png`,
    dimensions: [0.1, 0.1, 0.01],
    offset: [0, 0.0013, 0.0022],
    rotation: [0, 0, 0],
    scale: [2.08, 2.1, 2.59],
    attachTo: 'wall-side',
  },
  {
    id: 'toaster',
    category: 'appliance',
    name: 'Toaster',
    tags: ['countertop', 'electronics'],
    thumbnail:
      `${ASSET_BASE}/items/system/toaster/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/toaster/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/toaster/floor-plan.png`,
    dimensions: [0.28, 0.23, 0.17],
    offset: [-0.0057, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kettle',
    category: 'appliance',
    name: 'Kettle',
    tags: [
      'kettle',
      'teapot',
      'boiler',
      'electric',
      'kitchen',
      'appliance',
      'metal',
      'steel',
      'modern',
      'tea',
      'coffee',
      'boiling',
      'beverage',
      'breakfast',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/kettle/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/kettle/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/kettle/floor-plan.png`,
    dimensions: [0.24, 0.25, 0.18],
    offset: [-0.026, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'hydrant',
    category: 'appliance',
    name: 'Hydrant',
    tags: [
      'hydrant',
      'faucet',
      'spigot',
      'valve',
      'metal',
      'iron',
      'industrial',
      'vintage',
      'retro',
      'plumbing',
      'water',
      'utility',
      'outdoor',
      'garden',
      'red',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/hydrant/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/hydrant/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/hydrant/floor-plan.png`,
    dimensions: [0.64, 0.88, 0.64],
    offset: [-0.0046, 0, -0.0008],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fire-detector',
    category: 'appliance',
    name: 'Fire Detector',
    tags: [
      'detector',
      'alarm',
      'sensor',
      'smoke',
      'alert',
      'safety',
      'security',
      'protection',
      'appliance',
      'white',
      'plastic',
      'minimalist',
      'modern',
      'warning',
      'electronic',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/fire-detector/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/fire-detector/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/fire-detector/floor-plan.png`,
    dimensions: [0.12, 0.19, 0.07],
    offset: [0.0281, 0.012, 0.0015],
    rotation: [0, 0, 0],
    scale: [0.9, 1.4, 0.7],
    attachTo: 'wall',
  },
  {
    id: 'smoke-detector',
    category: 'appliance',
    name: 'Smoke Detector',
    tags: ['ceiling', 'safety'],
    thumbnail:
      `${ASSET_BASE}/items/system/smoke-detector/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/smoke-detector/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/smoke-detector/floor-plan.png`,
    dimensions: [0.16, 0.05, 0.16],
    offset: [0, 0.0492, 0],
    rotation: [Math.PI, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
  },
  {
    id: 'coffee-machine',
    category: 'appliance',
    name: 'Coffee Machine',
    tags: [
      'coffee',
      'machine',
      'maker',
      'espresso',
      'brewer',
      'kitchen',
      'appliance',
      'modern',
      'metal',
      'sleek',
      'black',
      'silver',
      'beverage',
      'brewing',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/coffee-machine/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/coffee-machine/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/coffee-machine/floor-plan.png`,
    dimensions: [0.16, 0.24, 0.23],
    offset: [0.0003, 0.0003, -0.0366],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ceiling-fan',
    category: 'appliance',
    name: 'Ceiling fan',
    tags: [
      'fan',
      'ventilator',
      'cooling',
      'airflow',
      'blades',
      'modern',
      'industrial',
      'metal',
      'wood',
      'appliance',
      'ventilation',
      'breeze',
      'climate',
      'circulation',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/ceiling-fan/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/ceiling-fan/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/ceiling-fan/floor-plan.png`,
    dimensions: [0.92, 0.35, 1.04],
    offset: [-0.1371, 0.3448, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [{ kind: 'toggle' }],
      effects: [{ kind: 'animation', clips: { on: 'On' } }],
    },
  },
  {
    id: 'iron',
    category: 'appliance',
    name: 'Iron',
    tags: [
      'iron',
      'steamer',
      'laundry',
      'clothing',
      'modern',
      'metal',
      'plastic',
      'ceramic',
      'garment',
      'pressing',
      'household',
      'utility',
      'appliance',
      'sleek',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/iron/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/iron/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/iron/floor-plan.png`,
    dimensions: [0.36, 0.24, 0.21],
    offset: [0.026, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'air-conditioning',
    category: 'appliance',
    name: 'Air Conditioning',
    tags: [
      'conditioner',
      'cooling',
      'hvac',
      'appliance',
      'electronic',
      'modern',
      'minimalist',
      'white',
      'climate',
      'temperature',
      'ventilation',
      'airflow',
      'comfort',
      'sleek',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/air-conditioning/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/air-conditioning/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/air-conditioning/floor-plan.png`,
    dimensions: [1.56, 0.6, 0.41],
    offset: [0, 0.3, 0.2018],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'computer',
    category: 'appliance',
    name: 'Computer',
    tags: [
      'computer',
      'desktop',
      'workstation',
      'monitor',
      'technology',
      'office',
      'electronics',
      'modern',
      'sleek',
      'metal',
      'silver',
      'minimalist',
      'hardware',
      'productivity',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/computer/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/computer/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/computer/floor-plan.png`,
    dimensions: [0.68, 0.48, 0.19],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'alarm-keypad',
    category: 'appliance',
    name: 'Alarm Keypad',
    tags: [
      'alarm',
      'keypad',
      'panel',
      'security',
      'interface',
      'controller',
      'modern',
      'minimalist',
      'digital',
      'plastic',
      'white',
      'electronic',
      'safety',
      'automation',
      'smart',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/alarm-keypad/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/alarm-keypad/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/alarm-keypad/floor-plan.png`,
    dimensions: [0.18, 0.13, 0.03],
    offset: [0, 0.0671, -0.0002],
    rotation: [1.5708, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'ev-wall-charger',
    category: 'appliance',
    name: 'Ev-wall-charger',
    tags: [
      'charger',
      'station',
      'electric',
      'vehicle',
      'automotive',
      'garage',
      'modern',
      'minimalist',
      'power',
      'energy',
      'appliance',
      'tech',
      'sleek',
      'plastic',
      'black',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/ev-wall-charger/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/ev-wall-charger/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/ev-wall-charger/floor-plan.png`,
    dimensions: [0.29, 0.65, 0.17],
    offset: [-0.0677, 0.2979, 0.1503],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall',
  },
  {
    id: 'electric-panel',
    category: 'appliance',
    name: 'Electric Panel',
    tags: [
      'breaker',
      'box',
      'fusebox',
      'electrical',
      'utility',
      'industrial',
      'metal',
      'steel',
      'power',
      'circuit',
      'technical',
      'maintenance',
      'energy',
      'appliance',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/electric-panel/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/electric-panel/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/electric-panel/floor-plan.png`,
    dimensions: [0.4, 0.98, 0.11],
    offset: [0, 0.0036, 0.0611],
    rotation: [0, 0, 0],
    scale: [0.61, 0.74, 0.7],
    attachTo: 'wall-side',
  },
  {
    id: 'bathroom-sink',
    category: 'bathroom',
    name: 'Bathroom Sink',
    tags: [
      'sink',
      'basin',
      'lavatory',
      'washbasin',
      'vanity',
      'modern',
      'minimalist',
      'ceramic',
      'porcelain',
      'white',
      'plumbing',
      'washing',
      'bathroom',
      'hygiene',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/bathroom-sink/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/bathroom-sink/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/bathroom-sink/floor-plan.png`,
    dimensions: [1.83, 0.97, 0.63],
    offset: [0.1037, 0, 0.0221],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shower-angle',
    category: 'bathroom',
    name: 'Angle Shower',
    tags: [
      'shower',
      'enclosure',
      'cubicle',
      'modern',
      'glass',
      'corner',
      'bathroom',
      'chrome',
      'minimalist',
      'washing',
      'hygiene',
      'plumbing',
      'stall',
      'sleek',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/shower-angle/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/shower-angle/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/shower-angle/floor-plan.png`,
    dimensions: [0.83, 1.81, 0.83],
    offset: [0.4102, 0, -0.4102],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toilet-paper',
    category: 'bathroom',
    name: 'Toilet Paper',
    tags: ['wall', 'decor'],
    thumbnail:
      `${ASSET_BASE}/items/system/toilet-paper/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/toilet-paper/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/toilet-paper/floor-plan.png`,
    dimensions: [0.26, 0.27, 0.24],
    offset: [0, 0.145, 0.1147],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'washing-machine',
    category: 'bathroom',
    name: 'Washing Machine',
    tags: ['floor', 'large', 'electronics'],
    thumbnail:
      `${ASSET_BASE}/items/system/washing-machine/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/washing-machine/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/washing-machine/floor-plan.png`,
    dimensions: [0.6, 0.86, 0.53],
    offset: [0, 0, -0.0114],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shower-rug',
    category: 'bathroom',
    name: 'Shower Rug',
    tags: [
      'rug',
      'mat',
      'bathmat',
      'absorbent',
      'cotton',
      'chenille',
      'modern',
      'soft',
      'minimalist',
      'spa',
      'bathroom',
      'hygiene',
      'plush',
      'microfiber',
      'woven',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/shower-rug/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/shower-rug/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/shower-rug/floor-plan.png`,
    dimensions: [0.77, 0.03, 0.48],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.03 },
  },
  {
    id: 'bathtub',
    category: 'bathroom',
    name: 'Bathtub',
    tags: [
      'bathtub',
      'tub',
      'bath',
      'soaking',
      'modern',
      'minimalist',
      'porcelain',
      'acrylic',
      'ceramic',
      'bathroom',
      'relaxation',
      'spa',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/bathtub/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/bathtub/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/bathtub/floor-plan.png`,
    dimensions: [2.34, 0.79, 1.11],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'laundry-bag',
    category: 'bathroom',
    name: 'Laundry Bag',
    tags: [
      'laundry',
      'bag',
      'hamper',
      'basket',
      'canvas',
      'fabric',
      'storage',
      'organization',
      'modern',
      'minimalist',
      'utility',
      'cleaning',
      'linen',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/laundry-bag/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/laundry-bag/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/laundry-bag/floor-plan.png`,
    dimensions: [0.46, 0.78, 0.48],
    offset: [0, 0, -0.0006],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shower-square',
    category: 'bathroom',
    name: 'Squared Shower',
    tags: ['floor', 'large'],
    thumbnail:
      `${ASSET_BASE}/items/system/shower-square/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/shower-square/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/shower-square/floor-plan.png`,
    dimensions: [0.81, 1.8, 0.81],
    offset: [0.4, 0, -0.3995],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'drying-rack',
    category: 'bathroom',
    name: 'Drying Rack',
    tags: [
      'dryer',
      'rack',
      'airer',
      'laundry',
      'hanging',
      'organizer',
      'metal',
      'steel',
      'modern',
      'minimalist',
      'storage',
      'bathroom',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/drying-rack/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/drying-rack/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/drying-rack/floor-plan.png`,
    dimensions: [1.79, 1.05, 0.58],
    offset: [0, -0.0058, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toilet',
    category: 'bathroom',
    name: 'Toilet',
    tags: ['floor', 'large'],
    thumbnail:
      `${ASSET_BASE}/items/system/toilet/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/toilet/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/toilet/floor-plan.png`,
    dimensions: [0.42, 0.82, 0.72],
    offset: [0, 0, -0.2393],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'microwave',
    category: 'kitchen',
    name: 'Microwave',
    tags: [
      'microwave',
      'oven',
      'appliance',
      'kitchen',
      'cooking',
      'heating',
      'metal',
      'steel',
      'modern',
      'sleek',
      'black',
      'silver',
      'electronics',
      'glass',
      'contemporary',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/microwave/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/microwave/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/microwave/floor-plan.png`,
    dimensions: [0.52, 0.27, 0.41],
    offset: [0, 0, -0.0225],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'cutting-board',
    category: 'kitchen',
    name: 'Cutting Board',
    tags: [
      'board',
      'wood',
      'kitchen',
      'prep',
      'chopping',
      'serving',
      'block',
      'rustic',
      'culinary',
      'timber',
      'natural',
      'chef',
      'cooking',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/cutting-board/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/cutting-board/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/cutting-board/floor-plan.png`,
    dimensions: [0.27, 0.07, 0.41],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-utensils',
    category: 'kitchen',
    name: 'Kitchen Utensils',
    tags: [
      'utensils',
      'tools',
      'kitchenware',
      'cooking',
      'prep',
      'steel',
      'silicone',
      'wood',
      'modern',
      'gadgets',
      'accessories',
      'silverware',
      'chef',
      'serving',
      'baking',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/kitchen-utensils/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/kitchen-utensils/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/kitchen-utensils/floor-plan.png`,
    dimensions: [0.23, 0.49, 0.21],
    offset: [0.0184, 0, 0.0165],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-counter',
    category: 'kitchen',
    name: 'Kitchen Counter',
    tags: [
      'counter',
      'countertop',
      'island',
      'surface',
      'workspace',
      'stone',
      'granite',
      'marble',
      'modern',
      'kitchen',
      'cooking',
      'prep',
      'sleek',
      'polished',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/kitchen-counter/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/kitchen-counter/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/kitchen-counter/floor-plan.png`,
    dimensions: [1.96, 0.73, 0.63],
    offset: [0.0012, 0, -0.0004],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.73 },
  },
  {
    id: 'hood',
    category: 'kitchen',
    name: 'Hood',
    tags: [
      'hood',
      'vent',
      'extractor',
      'ventilation',
      'kitchen',
      'cooking',
      'appliance',
      'metal',
      'steel',
      'stainless',
      'modern',
      'sleek',
      'industrial',
      'minimalist',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/hood/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/hood/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/hood/floor-plan.png`,
    dimensions: [1.21, 0.52, 0.51],
    offset: [0, 0.2718, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'wooden-kitchen-bar-moa2hhh4',
    category: 'kitchen',
    name: 'Kitchen Bar',
    tags: [
      'bar',
      'counter',
      'island',
      'breakfast',
      'modern',
      'contemporary',
      'wood',
      'stone',
      'quartz',
      'seating',
      'dining',
      'prep',
      'entertaining',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/wooden-kitchen-bar-moa2hhh4/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/wooden-kitchen-bar-moa2hhh4/models/item_model_c6iR1M2eE2I8k5M3.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/wooden-kitchen-bar-moa2hhh4/floor-plan.png`,
    dimensions: [2.5, 1.06, 0.96],
    offset: [0.0003, 0.5322, -0.0024],
    rotation: [0, 0, 0],
    scale: [2.49, 2.49, 2.49],
    surface: { height: 1.06 },
  },
  {
    id: 'kitchen-cabinet',
    category: 'kitchen',
    name: 'Kitchen Cabinet',
    tags: [
      'cabinet',
      'cupboard',
      'storage',
      'kitchen',
      'shaker',
      'pantry',
      'wood',
      'timber',
      'modern',
      'contemporary',
      'minimalist',
      'organization',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/kitchen-cabinet/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/kitchen-cabinet/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/kitchen-cabinet/floor-plan.png`,
    dimensions: [1.65, 1.09, 0.77],
    offset: [0, 0.0004, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 1.09 },
  },
  {
    id: 'kitchen',
    category: 'kitchen',
    name: 'Kitchen',
    tags: [
      'kitchen',
      'cabinetry',
      'cabinet',
      'island',
      'cooking',
      'storage',
      'modern',
      'contemporary',
      'minimalist',
      'wood',
      'marble',
      'culinary',
      'pantry',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/kitchen/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/kitchen/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/kitchen/floor-plan.png`,
    dimensions: [2.38, 1.03, 0.84],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.797 },
  },
  {
    id: 'frying-pan',
    category: 'kitchen',
    name: 'Frying Pan',
    tags: [
      'frying',
      'pan',
      'skillet',
      'cookware',
      'kitchen',
      'cooking',
      'metal',
      'steel',
      'nonstick',
      'culinary',
      'modern',
      'chef',
      'stove',
      'utensil',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/frying-pan/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/frying-pan/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/frying-pan/floor-plan.png`,
    dimensions: [0.36, 0.09, 0.64],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fruits',
    category: 'kitchen',
    name: 'Fruits',
    tags: [
      'fruit',
      'produce',
      'food',
      'kitchen',
      'dining',
      'centerpiece',
      'tabletop',
      'vibrant',
      'fresh',
      'organic',
      'natural',
      'accessory',
      'decor',
      'colorful',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/fruits/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/fruits/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/fruits/floor-plan.png`,
    dimensions: [0.39, 0.27, 0.39],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fridge',
    category: 'kitchen',
    name: 'Fridge',
    tags: [
      'fridge',
      'refrigerator',
      'freezer',
      'appliance',
      'kitchen',
      'storage',
      'cooling',
      'metal',
      'steel',
      'modern',
      'industrial',
      'minimalist',
      'silver',
      'sleek',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/fridge/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/fridge/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/fridge/floor-plan.png`,
    dimensions: [0.7, 1.92, 0.72],
    offset: [0, 0, -0.0507],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-shelf',
    category: 'kitchen',
    name: 'Kitchen Shelf',
    tags: [
      'shelf',
      'shelving',
      'rack',
      'ledge',
      'storage',
      'organizer',
      'kitchen',
      'pantry',
      'modern',
      'minimalist',
      'industrial',
      'wood',
      'metal',
      'utility',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/kitchen-shelf/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/kitchen-shelf/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/kitchen-shelf/floor-plan.png`,
    dimensions: [2.21, 0.89, 0.52],
    offset: [-0.0009, 0.4478, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
  },
  {
    id: 'wine-bottle',
    category: 'kitchen',
    name: 'Wine Bottle',
    tags: ['countertop', 'decor'],
    thumbnail:
      `${ASSET_BASE}/items/system/wine-bottle/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/wine-bottle/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/wine-bottle/floor-plan.png`,
    dimensions: [0.38, 0.35, 0.17],
    offset: [-0.0461, 0, 0.0135],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'stove',
    category: 'kitchen',
    name: 'Stove',
    tags: ['floor', 'large'],
    thumbnail:
      `${ASSET_BASE}/items/system/stove/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/stove/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/stove/floor-plan.png`,
    dimensions: [0.92, 0.85, 0.76],
    offset: [0.0043, 0, -0.0505],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ball',
    category: 'outdoor',
    name: 'Ball',
    tags: [
      'ball',
      'sphere',
      'orb',
      'globe',
      'round',
      'modern',
      'minimalist',
      'decor',
      'garden',
      'patio',
      'sculpture',
      'ornament',
      'accent',
      'circular',
      'contemporary',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/ball/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/ball/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/ball/floor-plan.png`,
    dimensions: [0.24, 0.24, 0.24],
    offset: [-0.0001, 0.1194, -0.0001],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bush',
    category: 'outdoor',
    name: 'Bush',
    tags: [
      'bush',
      'shrub',
      'plant',
      'greenery',
      'foliage',
      'hedge',
      'natural',
      'organic',
      'lush',
      'landscaping',
      'garden',
      'yard',
      'botanical',
      'outdoor',
      'decorative',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/bush/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/bush/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/bush/floor-plan.png`,
    dimensions: [3, 1.04, 1.01],
    offset: [-0.1463, 0.0094, -0.113],
    rotation: [0, 0, 0],
    scale: [0.96, 0.96, 0.96],
  },
  {
    id: 'basket-hoop',
    category: 'outdoor',
    name: 'Basket Hoop',
    tags: [
      'hoop',
      'basketball',
      'rim',
      'net',
      'goal',
      'sporty',
      'recreation',
      'outdoor',
      'metal',
      'steel',
      'athletic',
      'game',
      'play',
      'leisure',
      'activity',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/basket-hoop/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/basket-hoop/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/basket-hoop/floor-plan.png`,
    dimensions: [0.58, 1.78, 0.56],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'parking-spot',
    category: 'outdoor',
    name: 'Parking Spot',
    tags: [
      'parking',
      'space',
      'stall',
      'driveway',
      'pavement',
      'asphalt',
      'concrete',
      'urban',
      'industrial',
      'utility',
      'vehicle',
      'outdoor',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/parking-spot/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/parking-spot/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/parking-spot/floor-plan.png`,
    dimensions: [4.95, 0.12, 2.28],
    offset: [0, 0.0121, 0.015],
    rotation: [0, 0, 0],
    scale: [0.9, 1, 0.78],
    surface: { height: 0.015 },
  },
  {
    id: 'palm',
    category: 'outdoor',
    name: 'Palm',
    tags: [
      'palm',
      'tree',
      'plant',
      'tropical',
      'exotic',
      'foliage',
      'greenery',
      'botanical',
      'garden',
      'patio',
      'outdoor',
      'lush',
      'organic',
      'nature',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/palm/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/palm/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/palm/floor-plan.png`,
    dimensions: [0.525, 4.5, 0.496],
    offset: [0, 0.08, 0],
    rotation: [0, 0, 0],
    scale: [0.37, 0.37, 0.37],
  },
  {
    id: 'sunbed',
    category: 'outdoor',
    name: 'Sunbed',
    tags: ['leisure', 'seating', 'floor'],
    thumbnail:
      `${ASSET_BASE}/items/system/sunbed/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/sunbed/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/sunbed/floor-plan.png`,
    dimensions: [0.86, 1.13, 1.01],
    offset: [0, 0.0516, 0.0137],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fir-tree',
    category: 'outdoor',
    name: 'Fir',
    tags: [
      'fir',
      'tree',
      'plant',
      'evergreen',
      'conifer',
      'foliage',
      'greenery',
      'natural',
      'garden',
      'outdoor',
      'botanical',
      'rustic',
      'alpine',
      'woodland',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/fir-tree/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/fir-tree/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/fir-tree/floor-plan.png`,
    dimensions: [0.27, 3, 0.23],
    offset: [0.02, 0.05, -0.06],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tree',
    category: 'outdoor',
    name: 'Tree',
    tags: ['vegetation'],
    thumbnail:
      `${ASSET_BASE}/items/system/tree/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/tree/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/tree/floor-plan.png`,
    dimensions: [0.79, 5, 0.85],
    offset: [-0.02, 0.17, -0.04],
    rotation: [0, 0, 0],
    scale: [0.65, 0.65, 0.65],
  },
  {
    id: 'skate',
    category: 'outdoor',
    name: 'Skate',
    tags: ['leisure', 'kids', 'floor'],
    thumbnail:
      `${ASSET_BASE}/items/system/skate/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/skate/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/skate/floor-plan.png`,
    dimensions: [0.86, 0.11, 0.2],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: '1967-chevrolet-camaro-moa24wsf',
    category: 'outdoor',
    name: '1967 Chevrolet Camaro',
    tags: ['car'],
    thumbnail:
      `${ASSET_BASE}/items/system/1967-chevrolet-camaro-moa24wsf/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/1967-chevrolet-camaro-moa24wsf/models/item_model_vUIp1N69V9RXLqoJ.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/1967-chevrolet-camaro-moa24wsf/floor-plan.png`,
    dimensions: [4.09, 1.22, 1.89],
    offset: [-0.0018, 0.5987, 0.0205],
    rotation: [0, 0, 0],
    scale: [4.09, 4.09, 4.09],
  },
  {
    id: 'outdoor-playhouse',
    category: 'outdoor',
    name: 'Outdoor Playhouse',
    tags: [
      'playhouse',
      'cottage',
      'cabin',
      'fort',
      'wood',
      'cedar',
      'garden',
      'backyard',
      'kids',
      'children',
      'play',
      'recreation',
      'outdoor',
      'rustic',
      'timber',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/outdoor-playhouse/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/outdoor-playhouse/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/outdoor-playhouse/floor-plan.png`,
    dimensions: [0.3, 0.47, 0.72],
    offset: [-0.0062, 0, -0.0268],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'patio-umbrella',
    category: 'outdoor',
    name: 'Patio Umbrella',
    tags: [
      'umbrella',
      'parasol',
      'shade',
      'canopy',
      'sunshade',
      'outdoor',
      'patio',
      'garden',
      'modern',
      'polyester',
      'fabric',
      'aluminum',
      'poolside',
      'protection',
      'summer',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/patio-umbrella/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/patio-umbrella/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/patio-umbrella/floor-plan.png`,
    dimensions: [0.139, 3.603, 0.15],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'pillar',
    category: 'outdoor',
    name: 'Pillar',
    tags: [
      'pillar',
      'column',
      'pedestal',
      'plinth',
      'stone',
      'concrete',
      'classical',
      'architectural',
      'garden',
      'ornament',
      'decoration',
      'support',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/pillar/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/pillar/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/pillar/floor-plan.png`,
    dimensions: [0.34, 1.26, 0.3],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'scooter',
    category: 'outdoor',
    name: 'Scooter',
    tags: [
      'scooter',
      'kickscooter',
      'transport',
      'mobility',
      'outdoor',
      'wheels',
      'metal',
      'aluminum',
      'modern',
      'sleek',
      'urban',
      'active',
      'travel',
      'ride',
      'commute',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/scooter/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/scooter/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/scooter/floor-plan.png`,
    dimensions: [0.85, 0.85, 0.45],
    offset: [0.1127, 0.0017, 0.1744],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tesla',
    category: 'outdoor',
    name: 'Tesla Model Y',
    tags: [
      'tesla',
      'car',
      'vehicle',
      'automobile',
      'electric',
      'modern',
      'minimalist',
      'sleek',
      'metal',
      'glass',
      'luxury',
      'transportation',
      'commuting',
    ],
    thumbnail:
      `${ASSET_BASE}/items/system/tesla/thumbnail.png`,
    src: `${ASSET_BASE}/items/system/tesla/model.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/system/tesla/floor-plan.png`,
    dimensions: [1.98, 1.62, 4.76],
    offset: [0.0039, -0.0102, -0.0148],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'dishwasher-movn72ls',
    category: 'appliance',
    name: 'Dishwasher',
    tags: ['dishwasher', 'appliance', 'kitchen', 'floor'],
    thumbnail:
      `${ASSET_BASE}/items/users/user_7hUFMrlrAX1vtIwT/dishwasher-movn72ls/thumbnail.png`,
    src: `${ASSET_BASE}/items/users/user_7hUFMrlrAX1vtIwT/dishwasher-movn72ls/models/item_model_fFvQuIjpPISAraGN.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/users/user_7hUFMrlrAX1vtIwT/dishwasher-movn72ls/floor-plan.png`,
    dimensions: [0.79, 1.01, 0.76],
    offset: [0.0026, 0.5004, 0.0011],
    rotation: [0, -0.0349, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fireplace-movn1fnn',
    category: 'furniture',
    name: 'Fireplace',
    tags: ['fireplace', 'hearth', 'mantel', 'wall'],
    thumbnail:
      `${ASSET_BASE}/items/users/user_7hUFMrlrAX1vtIwT/fireplace-movn1fnn/thumbnail.png`,
    src: `${ASSET_BASE}/items/users/user_7hUFMrlrAX1vtIwT/fireplace-movn1fnn/models/item_model_vNBpPC3gCrIIqFUS.glb`,
    floorPlanUrl:
      `${ASSET_BASE}/items/users/user_7hUFMrlrAX1vtIwT/fireplace-movn1fnn/floor-plan.png`,
    dimensions: [1, 0.83, 0.18],
    offset: [-0.0001, 0.4116, -0.0015],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
]

export function getDefaultCatalogItem(category: string | null | undefined): AssetInput | null {
  if (!category) return null
  return CATALOG_ITEMS.find((item) => item.category === category) ?? null
}
